### ISSUE TITLE
Roadmap to legal compliance

### ISSUE THREAD

**Issue by tobozo** [lovyan03/LovyanGFX#4]
- [ ] Documentation
  - [ ] Use Doxygen ? [automated example with ESP32-targz](https://tobozo.github.io/ESP32-targz/ESP32-targz_8h.html)
  - [ ] How many languages ? ( current candidates : en / fr / jp )
  - [ ] ReadME: detailed scope of the library
    - software scope: AVR, ESP85266, ESP32-Arduino, esp-idf
    - hardware scope: simultaneously drive up to 8 (or more?) SPI displays
  - [ ] Gitter community ?
  - [ ] Wiki (can receive public contributions, needs to be enabled in github project settings) ?
- [ ] License
  - [x] Main license (MIT)
  - [ ] Inherited licenses template:
    - 1 Initial *unmodified* license
    - 2 Additional license
    - 3 Project specific notes
  - [ ] fonts need distinct license
- [ ] Examples folder
  - [ ] Needs hierarchy (Basic/Advanced, ESP8266/ESP32/AVR)
  - [ ] Can act as unit tests (travis or github actions)
- [ ] Unimplemented functions
  - [ ] Upper/lower layer interoperability (esp-idf, chimera-core)
  - [ ] Known API friendliness (M5Stack, TFT_eSPI)

**Comment by summerfind** [comment]
Hi all. I got compiling error: 'LGFX_SPI' in namespace 'lgfx' does not name a template type for the line: 
static lgfx::LGFX_SPI<LGFX_Config> tft; 
how to fix?
Thanks.

**Comment by tobozo** [comment]
@summerfind please don't necro bump and only create an issue if you didn't find an existing post with a solution to your problem


locking this post
